vich_uploader:
    db_driver: orm

    mappings:
       restaurants_pictures:
           uri_prefix: /images/restaurants
           upload_destination: '%kernel.project_dir%/public/images/restaurants'
           namer: Vich\UploaderBundle\Naming\UniqidNamer